language: node_js
node_js:
- node
install:
- npm install
- npm install -g gulp-cli
script:
- npm test
deploy:
  provider: gae
  project: luna-224018
  keyfile: deploy/AppEngine.json
before_install:
- openssl aes-256-cbc -K $encrypted_51986a45e90d_key -iv $encrypted_51986a45e90d_iv
  -in AppEngine.json.enc -out AppEngine.json -d
