language: node_js
node_js:
- node
install:
- npm install
- npm install -g gulp-cli
script:
- npm test
deploy:
  provider: gae
  project: luna-224018
  keyfile: deploy/AppEngine.json
before_install:
- openssl aes-256-cbc -K $encrypted_323c3ce922a5_key -iv $encrypted_323c3ce922a5_iv
  -in deploy\\AppEngine.json.enc -out deploy\\AppEngine.json -d
