---
shortname: # This is the name that will be prefixed to logs from *this* bot instance.
APIKeys:
  discord: # This is the only value required to be in your configuration. Paste the key from the Discord API console here.
logLevel: 0 # The minimum log level that will be printed. 0 is info, 1 is warnings, 2 is errors.
defaultPermissionLevel: 0 # The bot has its own simple permission system, used to guard access to powerful commands. This sets every user's default.
intentsResolutionMethod: useDefault # Determines how intent configuration resolution will be handled. Set to "useCustom" or "concatenate" to use your own intents or combine them with the defaults, respectively.
intents:
- name: greeting # names must be unique
  models: # Models are what get fed to the natural language system to train it to interpret messages.
  - hello
  - hi
  - greetings
  - welcome
  handler: basic-response # Handler that picks a random response from the provided list.
  data:
    responses: # Provide responses to be randomly replied with for the provided models.
    - Hello!
    - Hi!
    - Greetings.
    - Aloha.
    - Salutations.
- name: despacito
  models:
  - that's so sad
  - play despacito
  - that's so sad play despacito
  - despacito
  handler: basic-response
  data:
    responses:
    - 'Here''s some Desapcito: https: //www.youtube.com/watch?v=kJQP7kiw5Fk'
    - Do I *look* like Alexa to you?
- name: goodnight
  models:
  - goodnight
  - good night
  - buenos noches
  handler: basic-response
  data:
    responses:
    - Goodnight!
    - Have a good night!
    - See you tomorrow, I guess?
- name: capability-query
  models:
  - what can you do?
  - help
  - what can I say?
  handler: basic-response
  data:
    responses:
    - You can say "make a temporary channel", and I'll create a voice channel that
      only exists as long as someone's in it. I don't do much yet, though. My developer's
      working on it.
- name: declaration-of-love
  models:
  - I love you
  - ily
  handler: basic-response
  data:
    responses:
    - Aww, I love you too!
    - \*blushes\* # You can use any of Discord's standard text formatting.
- name: ip-finder
  permissionLevel: 5 # You must be previliged to know the bot's IP address.
  models:
  - where am I?
  - what is my IP address
- name: bot-shutdown
  permissionLevel: 5 
  models:
  - shut down
  - shutdown
  - go offline
  data:
    responses:
    - Ok. Goodbye!
    - I'll be back.
    handlerSpecific: # The responses field must always be an array of strings. The intentSpecific field allows for infinite variety, as needed by this specific handler.
      shutdownDelay: 3000 
- name: temporary-voice-channel # If no handler is specified, the bot tries to load a handler named the same as the intent.
  models:
  - make a temporary voice channel
  - create a channel
  - make a vc
  - make a temporary channel
  - make a channel
  - create a temporary channel
  - create a temporary voice channel
  - new channel
  - make a new channel
  - make a new channel please
  - new channel please
  data:
    questionData: # This handler asks the user a question to finish handling their request. (It's a limitation of natural.js that I can't get parameters from input.)
      questionMessage: # This is the question the user is asked. Multiple possibilities are encouraged.
      - Alright, what do you want to name it?
      - What do you want to call it?
      answeredResponseMessage: # When the bot has the user's response, it replies with one of these.
      - Alright, that's what I'll call it.
      - And so it was named.
      - Perfectly named. As all things should be.
      timeoutResponseMessage: # If the user takes too long, it replies with one of these. 
      - Never mind. I'll pick a name.
      - Alright. Guess I'll pick one.
      responseCheckIntervalMs: 500 # How often to check for a response...
      responseCheckDurationMs: 10000 # And how long to wait for a response.
      defaultResponses: # Acceptable default responses to the question, picked at random if the user takes too long.
      - Death Metal
      - Rainbows
      - Unicorns
      - Not Murder
      - The End Times
      - How 'Bout That Lotus, Eh?
      - Johnathan
      - The Council of Elrond
      - Generic channel name
      - Stuck in Vim
    responses:
    - 'welcome to your new channel: '
    - 'Here you go! Your new channel, fresh from the factory: '
    handlerSpecific:
      checkForMembersInterval: 5000 # How often to check if people are still in the voice channel
      bitrate: 16 # The default bitrate for newly created temporary voice channels.
- name: error-unknown # This intent is invoked when the bot has no goddamn clue what's going on.
  handler: basic-response
  data:
    responses:
    - I'm sorry, what was that?
    - I didn't understand. Could you rephrase that?
plugins: # Plugins add additional functionality. They don't currently each have any configuration options.
- presence-roles # Creates and assigns roles to people while they are in-game, and deletes them afterwards. Created roles look like @in:[Name of game].
- voice-scaling # For voice channels whose names end in a space-seperated number, E.G. "Hangouts 1", the bot will automatically create and destroy as many duplicate channels as needed for the number of people online. New channels will be auto-assigned to the lowest available number. 
