name: Deploy
on: [push, pull_request]
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1

            - name: Authenticate Docker
              run: docker login docker.pkg.github.com -u action -p ${{ secrets.GITHUB_TOKEN }}
