name: Publish
on: [push, pull_request]
jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1

            - name: Authenticate Docker
              run: docker login docker.pkg.github.com -u action -p ${{ secrets.GITHUB_TOKEN }}

            - name: Docker Build
              run: docker build -t docker.pkg.github.com/${{ env.GITHUB_REPOSITORY }}/discordbot-ts:${{ env.GITHUB_REF }}

            - name: Publish
              run: docker push docker.pkg.github.com/${{ env.GITHUB_REPOSITORY }}/discordbot-ts:${{ env.GITHUB_REF }}
