name: Publish
on: [push, pull_request]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set variables
        run: |
          echo "IMAGE_NAME=docker.pkg.github.com/$GITHUB_REPOSITORY/bot" >> $GITHUB_ENV

      - name: Authenticate Docker
        run: docker login docker.pkg.github.com -u action -p ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        run: docker build . -t built_image

      - name: "Docker: Tag Latest"
        run: docker image tag built_image $IMAGE_NAME:latest
        if: github.ref == 'refs/heads/master'

      - name: "Docker: Publish Latest"
        run: docker push $IMAGE_NAME:latest
        if: github.ref == 'refs/heads/master'

      - name: Get version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      - name: "Docker: Tag Version"
        run: docker image tag built_image $IMAGE_NAME:$VERSION
        if: startsWith(github.ref, 'refs/tags/')

      - name: "Docker: Publish Version"
        run: docker push $IMAGE_NAME:$VERSION
        if: startsWith(github.ref, 'refs/tags/')
