name: Testing
on: [push, pull_request]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1

            - name: Authenticate Docker
              run: docker login docker.pkg.github.com -p ${{ secrets.GITHUB_TOKEN }}
