name: Publish
on: [push, pull_request]
jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1

            - name: Set variables
              run: |
                  ::set-env name=IMAGE_NAME::"docker.pkg.github.com/$GITHUB_REPOSITORY/discordbot-ts:$([ -z "$(git tag -l --points-at HEAD)" ] && echo "$(git branch --show-current)" || echo "$(git tag -l --points-at HEAD)")"

            - name: Authenticate Docker
              run: docker login docker.pkg.github.com -u action -p ${{ secrets.GITHUB_TOKEN }}

            - name: Docker Build
              run: docker build -t $IMAGE_NAME

            - name: Publish
              run: docker push $IMAGE_NAME
