name: Publish
on: [push, pull_request]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set variables
        run: |
          echo "::set-env name=IMAGE_NAME::docker.pkg.github.com/$GITHUB_REPOSITORY/bot"

      - name: Authenticate Docker
        run: docker login docker.pkg.github.com -u action -p ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        run: docker build . -t built_image

      - name: "Docker: Tag Latest"
        run: docker image tag built_image $IMAGE_NAME:latest
        if: github.ref == 'refs/heads/master'

      - name: "Docker: Publish Latest"
        run: docker push $IMAGE_NAME:latest
        if: github.ref == 'refs/heads/master'
