name: Docs
on:
  push:
    branches:
      - master
    paths-ignore:
      - docs/**

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node v13
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: Install dependencies
        run: npm ci

      - name: Generate docs
        run: npm run docs

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/**
          git commit -m "Update docs"

      - name: Push docs
        run: git push origin master
        if: github.ref == 'refs/heads/master'
