name: Testing
on:
  push:
    paths: # Add anchor when available
      - "**.js"
      - "**.ts"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
  pull_request:
    paths: # Replace with alias to above anchor when available.
      - "**.js"
      - "**.ts"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
jobs:
  build:
    name: Builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Node v13
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Node v13
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: Install dependencies
        run: npm ci

      - name: Execute unit tests
        run: npm run test
